modLoader="javafml"

loaderVersion="${loader_version_range}"

license="MIT"

[[mods]]

modId="simplest_excavators"

version="1.1.4"

displayName="Simplest Excavators"

authors="IndEvo Studio"

description='''Vanilla excavators breaking in a 3x3 area.'''

[[dependencies.simplest_excavators]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.simplest_excavators]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.simplest_excavators]]
modId="simplest_compression"
mandatory=true
versionRange="[1.0.0,)"
ordering="NONE"
side="BOTH"