modLoader="javafml"

loaderVersion="${loader_version_range}"

license="MIT"

[[mods]]

modId="simplest_excavators"

version="1.1.5"

displayName="Simplest Excavators"

authors="Team Solar"

description='''Vanilla excavators breaking in a 3x3 area.'''
logoFile="icon.png"

[[dependencies.simplest_excavators]]
modId="forge"
mandatory=true
versionRange="${forge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.simplest_excavators]]
modId="minecraft"
mandatory=true
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"